
<!DOCTYPE html>
<html ng-app="eLearningApp">
    <!--[if IE 9 ]><html class="ie9"><![endif]-->
    <head>
        <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/img/favicon.ico" type="image/vnd.microsoft.icon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="format-detection" content="telephone=no">
        <meta charset="UTF-8">

        <meta name="description" content="Violate Responsive Admin Template">
        <meta name="keywords" content="Super Admin, Admin, Template, Bootstrap">

        <title>e-Learning</title>

        <!-- CSS -->
        <base href="<?php echo $this->basePath(); ?>/" />
    </head>
    <body ng-controller="mainController"> 
        <header id="header" class="media">
            <span > Welcome {{first_name}} {{last_name}}</span>

            <div id="time" class="pull-right" >
                <div class="btn-group">
                    <a href="logout" type="button">Log out</a>
                </div>
            </div>
        </header>
        
        <div style="min-height:800px;" ng-view >
            <?php echo $this->content; ?>
        </div>

    <!-- Javascript Libraries -->
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-1.2.26.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-route.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/application.js"></script>
    </body> 

</html>