
<!DOCTYPE html>
<html ng-app="">
    <!--[if IE 9 ]><html class="ie9"><![endif]-->
    <head>
        <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/img/favicon.ico" type="image/vnd.microsoft.icon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="format-detection" content="telephone=no">
        <meta charset="UTF-8">

        <meta name="description" content="Violate Responsive Admin Template">
        <meta name="keywords" content="Super Admin, Admin, Template, Bootstrap">

        <title></title>

        <!-- CSS -->
        <base href="<?php echo $this->basePath(); ?>/" />
    </head>
    <body> 
        <p>Zend Framework 2.3 </p>
    </body>

</html>