<html>
    <head>
     <!--<link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/img/favicon.ico" type="image/vnd.microsoft.icon">-->
      <meta name="keywords" content="">
        <!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#76c045">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#76c045">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="#76c045">
 <link href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">
          <link href="<?php echo $this->basePath(); ?>/css/bootstrap-responsive.css" rel="stylesheet">
            <link href="<?php echo $this->basePath(); ?>/css/bootstrap-responsive.min.css" rel="stylesheet">
              <link href="<?php echo $this->basePath(); ?>/css/font-awesome.css" rel="stylesheet">
                <link href="<?php echo $this->basePath(); ?>/css/font-awesome.min.css" rel="stylesheet">
                  <link href="<?php echo $this->basePath(); ?>/css/piro-box.css" rel="stylesheet">
                    <link href="<?php echo $this->basePath(); ?>/css/socialist.css" rel="stylesheet">
                      <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">
                       <link href="<?php echo $this->basePath(); ?>/css/style.min.css" rel="stylesheet">
    </head>
    <body>
    <div  class="container login-group" style="min-height: 400px; padding:10%;" >
    <div style=""><h2>Login for E-Learing Portal with your social media account or email address</h2></div>
            <div style="margin-left:25%;"><?php echo $this->content; ?>
            </div>
            </div>
            
             <script src="<?php echo $this->basePath(); ?>/js/angular/angular-1.2.26.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-route.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
             <script src="<?php echo $this->basePath(); ?>/js/bootstrap.js"></script>
             <script src="<?php echo $this->basePath(); ?>/js/bootstrap.min.js"></script>
              <script src="<?php echo $this->basePath(); ?>/js/enscroll.min.js"></script>
               <script src="<?php echo $this->basePath(); ?>/js/functions.js"></script>
                 <script src="<?php echo $this->basePath(); ?>/js/functions.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/application.js"></script>
    </body>
</html>
