<html>
    <head>
     <!--<link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/img/favicon.ico" type="image/vnd.microsoft.icon">-->
      <meta name="keywords" content="">
        <!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#76c045">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#76c045">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="#76c045">
    </head>
    <body>
            <?php echo $this->content; ?>
    </body>
</html>
