<html>
    <head>
    <link href="<?php echo $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">
          <link href="<?php echo $this->basePath(); ?>/css/bootstrap-responsive.css" rel="stylesheet">
            <link href="<?php echo $this->basePath(); ?>/css/bootstrap-responsive.min.css" rel="stylesheet">
              <link href="<?php echo $this->basePath(); ?>/css/font-awesome.css" rel="stylesheet">
                <link href="<?php echo $this->basePath(); ?>/css/font-awesome.min.css" rel="stylesheet">
                  <link href="<?php echo $this->basePath(); ?>/css/piro-box.css" rel="stylesheet">
                    <link href="<?php echo $this->basePath(); ?>/css/socialist.css" rel="stylesheet">
                      <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">
                       <link href="<?php echo $this->basePath(); ?>/css/style.min.css" rel="stylesheet">
<style>
.show-grid {
	width:100%;
	padding:10px 10px 10px 10px;
	float:left;
	}
</style>
    </head>
    <body>

<form role="form" method="post" id='userSignUp' action="userSignUp">
    <h2 class="m-t-0 m-b-15" style="color:#5a431b;">Sign Up</h2>
    <div id="signupPage">
        <div class="show-grid" >
            <div class="span2">Name : </div>
            <div class="span4"><input type="text" id="user_name" name="user_name" ng-model="user_name"></div>
              <div class="show-grid">
             <div class="span2">Select image to upload : </div>
              <div class="span6">
             <input type="file" id="fileToUpload" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit"></div></div>
              <div class="show-grid">
            <div class="span2">Designation : </div>
            <div class="span4"><input type="text" id="user_designation" name="user_designation" ng-model="user_designation"></div></div>
            <div class="show-grid">
            <div class="span2">Organization : </div>
            <div class="span4"><input type="text" id="user_organization" name="user_organization" ng-model="user_organization"></div></div>
            <div class="show-grid">
            <div class="span2">City : </div>
            <div class="span4"><input type="text" id="user_city" name="user_city" ng-model="user_city"></div></div>
            <div class="show-grid">
            <div class="span2">Country : </div>
            <div class="span4"><input type="text" id="user_country" name="user_country"  ng-model="user_country"></div></div>
            <div class="show-grid">
            <div class="span2">Phone : </div>
            <div class="span4"><input type="tel" id="user_phone" name="user_phone" ng-model="user_phone"></div></div>
            <div class="show-grid">
            <div class="span2">Business Email : </div>
            <div class="span4"><input type="email" id="business_email" name="business_email" ng-model="user_phone"></div></div>
 <div class="show-grid">
        <div class="span2">Google ID : </div>
        <div class="span4"> <input type="text" id="google_id" name="google_id" ng-model="google_id">
        
        <input type="hidden" id="login_source" name="login_source" value="facebook" ng-model="login_source"></div></div>
       <div class="show-grid">
            <div class="span5" style="text-align:right;" > 
        <button style="background:#333; color:#CCC; padding:10px 10px 10px 10px;">Submit</button></div></div>
    </div>        
</form>
<?php
die();
?>
 <script src="<?php echo $this->basePath(); ?>/js/angular/angular-1.2.26.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-route.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="<?php echo $this->basePath(); ?>/js/application.js"></script>
             <script src="<?php echo $this->basePath(); ?>/js/bootstrap.js"></script>
             <script src="<?php echo $this->basePath(); ?>/js/bootstrap.min.js"></script>
              <script src="<?php echo $this->basePath(); ?>/js/enscroll.min.js"></script>
               <script src="<?php echo $this->basePath(); ?>/js/functions.js"></script>
                 <script src="<?php echo $this->basePath(); ?>/js/jquery-1.8.3.min.js"></script>
                 <script src="<?php echo $this->basePath(); ?>/js/jquery-ui-1.8.2.custom.min.js"></script>
                 <script src="<?php echo $this->basePath(); ?>/js/jquery.masonry.js"></script>
                 <script src="<?php echo $this->basePath(); ?>/js/jquery.masonry.min.js"></script>
                 <script src="<?php echo $this->basePath(); ?>/js/jquery.socialist.js"></script>
</body>
</html>