
<form role="form" method="post" id='userSignUp' action="userSignUp">
    <h2 class="m-t-0 m-b-15" style="color:#5a431b;">Sign Up</h2>
    <div id="signupPage">
        <div>User ID : </div>
        <div><input type="text" name="user_id" ng-model="user_id"></div>

        <div>Password : </div>
        <div><input type="password" name="password" ng-model="user_password"></div>

        <div>Facebook ID : </div>
        <input type="text" name="facebook_id" ng-model="facebook_id">
        
        <button>Submit</button>
    </div>        
</form>
<?php
die();
?>